### ISSUE TITLE
Interruption of service?

### ISSUE THREAD

**Issue by tenprint** [Yelp/yelp-api#93]
I've been getting slow or non-reponses from the Yelp API today. I also received one instance of "INTERNAL_ERROR" response to my query.  I'm connecting using the Scribe library provide in the example code. Prior to today I haven't had any issues.  Is something going on with the service?  Thanks

Here's some of the error log:
` Process: com.[...], PID: 26642
                                                                          java.lang.RuntimeException: An error occurred while executing doInBackground()
[...]
Caused by: org.scribe.exceptions.OAuthConnectionException: There was a problem while creating a connection to the remote service.
                                                                              at org.scribe.model.Request.send(Request.java:70)
                                                                              at org.scribe.model.Request.send(Request.java:76)
                                                                              at com.[...].YelpAPI.sendRequestAndGetResponse(YelpAPI.java:120)
                                                                              at com.[...].YelpAPI.searchForBusinessesByLocation(YelpAPI.java:83)
                                                                              at
 [...]                                                                           
Caused by: java.net.ConnectException: failed to connect to api.yelp.com/104.16.57.23 (port 443): connect failed: ENETUNREACH (Network is unreachable)
                                                                              at libcore.io.IoBridge.connect(IoBridge.java:124)
                                                                              at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                              [...]                                                                            

Caused by: android.system.ErrnoException: connect failed: ENETUNREACH (Network is unreachable)
                                                                              at libcore.io.Posix.connect(Native Method)
                                                                              at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
                                                                              at libcore.io.IoBridge.connectErrno(IoBridge.java:137)
[...] `

**Comment by mittonk** [comment]
Hm, that does sound like connectivity issues but I haven't seen anything noteworthy today.

1. What do you see for "ping api.yelp.com"?  This will take OAuth, Java, and the Yelp API application layer out of the loop.
2. Have you tried pinging other, non-Yelp sites?  That'll check for issues earlier on the path to `api.yelp.com`.
3. Are you still seeing issues?
4. What's your `oauth_consumer_key`?  That'll help me check some logs from our end.  (Definitely _don't_ send any of the other OAuth items like consumer_secret for security reasons).

**Comment by tenprint** [comment]
Hi,

Thanks for the quick response.  

This issue hasn't seemed to happen in the last couple hours

1. Here's the ping response from the device:
![image](https://cloud.githubusercontent.com/assets/11450465/12502070/b67d4de4-c092-11e5-8236-1ddb862bb3b0.png)

2. I tried `ping google.com` and the results are a little slower, latency 52, 38, and 39 ms out of three tries

3. In the last couple hours, I haven't been seeing the issue.

4.  consumer key is oQTKYz6GmKD0u664grDIRA

Thanks

**Comment by mittonk** [comment]
Looks like this was a sporadic network blip --- things seem to be working better now.
